myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('postapp.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

postapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'postapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new/', login_required(views.New.as_view()), name='new'),
    path('edit/<int:pk>/', login_required(views.Edit.as_view()), name='edit'),
    path('delete/<int:pk>/', login_required(views.Delete.as_view()), name='delete'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('profile/<slug:profname>/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/<slug:profname>/', login_required(views.ProfileEditView.as_view()), name='profile_edit'),
    path('<slug:profname>/follow', views.follow_view, name='follow'),
    path('<slug:profname>/unfollow', views.unfollow_view, name='unfollow'),
    path('<postId>/like/', login_required(views.Likes.as_view()), name='like'),
    path('<postId>/comment/', login_required(views.AddComment.as_view()), name='comment'),
    path('delete/comment/<int:pk>/', login_required(views.DeleteComment.as_view()), name='delete_comment'),
    path('tag/<int:pk>', views.Tag.as_view(), name='tag'),
]

postapp/models.py
from django.db import models
from users.models import User


class Tag(models.Model):
    name = models.CharField(verbose_name='タグ', max_length=30)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey('users.User', on_delete=models.CASCADE)
    picture1 = models.ImageField(upload_to='image/posts/', blank=False, null=False)
    picture2 = models.ImageField(upload_to='image/posts/', blank=True, null=True)
    picture3 = models.ImageField(upload_to='image/posts/', blank=True, null=True)
    picture4 = models.ImageField(upload_to='image/posts/', blank=True, null=True)
    text = models.TextField(blank=True)
    tag = models.ManyToManyField(Tag, verbose_name='タグ')
    #relationは関連する記事がない場合記事を指定せずに保存できる。Postと紐づけるからself
    relation = models.ManyToManyField('self', verbose_name='関連', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.text


class Like(models.Model):
    author = models.ForeignKey('users.User', on_delete=models.CASCADE)
    post = models.ForeignKey('postapp.Post', on_delete=models.CASCADE)


class Comment(models.Model):
    author = models.ForeignKey('users.User', on_delete=models.CASCADE)
    post = models.ForeignKey('postapp.Post', on_delete=models.CASCADE)
    text = models.TextField(blank=False, null=False)


class Connection(models.Model):
    follower = models.ForeignKey('users.User', related_name='follower', on_delete=models.CASCADE)
    following = models.ForeignKey('users.User', related_name='following', on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}が{}をフォローしました".format(self.follower.profname, self.following.profname)

postapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model
from django import forms

from .models import Post
from users.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'profname', 'icon')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('picture1', 'picture2', 'picture3', 'picture4', 'text')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        # model = get_user_model()
        fields = ('icon', 'proftext')

    def __init__(self, email=None, profname=None, icon=None, proftext=None):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        #ユーザーの更新前の情報を挿入
        if email:
            self.fields['email'].widget.attrs['values'] = email
        if profname:
            self.fields['profname'].widget.attrs['values'] = profname
        if icon:
            self.fields['icon'].widget.attrs['values'] = icon
        if proftext:
            self.fields['proftext'].widget.attrs['values'] = proftext

    def update(self, user):
        user.icon = self.cleaned_data['icon']
        user.proftext = self.cleaned_data['proftext']
        user.save()

postapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.views.generic import TemplateView, ListView, CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.edit import CreateView
from django.views.decorators.http import require_POST
from django.views import View
from django.views import generic
from django.db.models import Count, Q
from .forms import LoginForm, SignUpForm, PostForm, ProfileForm
from .models import Post, Like, Comment, Tag, Connection
from users.models import User
from .helpers import get_current_user
from django.http import HttpResponseRedirect, Http404

class IndexView(ListView):
    model = Post
    template_name = 'postapp/index.html'
    paginate_by = 12
    queryset = Post.objects.order_by('created_at').reverse().annotate(Count('like', distinct=True), Count('comment', distinct=True))

    """ 検索機能 Text or Tag """
    def get_queryset(self):
        q_word = self.request.GET.get('keyword')

        if q_word:
            object_list = Post.objects.order_by('created_at').reverse().annotate(Count('like', distinct=True), Count('comment', distinct=True)).filter(Q(text__icontains=q_word) | Q(tag__name__icontains=q_word))
            messages.info(self.request, '{} の検索結果'.format(q_word))
        else:
            object_list = Post.objects.order_by('created_at').reverse().annotate(Count('like', distinct=True), Count('comment', distinct=True))
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        like_list = {}
        comment_list = {}
        for post in context['post_list']:
            like_list[post.id] = Like.objects.filter(post=post)
            comment_list[post.id] = Comment.objects.filter(post=post)
        context['like_list'] = like_list
        context['comment_list'] = comment_list
        return context


""" タグ一覧 """
class Tag(DetailView):
    model = Tag
    template_name = 'postapp/tag_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["posts_list"] = Post.objects.all().annotate(Count('like', distinct=True), Count('comment', distinct=True))
        like_list = {}
        comment_list = {}
        for post in context['posts_list']:
            like_list[post.id] = Like.objects.filter(post=post)
            comment_list[post.id] = Comment.objects.filter(post=post)
        context['like_list'] = like_list
        context['comment_list'] = comment_list
        return context


class New(CreateView):
    template_name = 'postapp/new.html'
    form_class = PostForm
    success_url = reverse_lazy('postapp:index')

    #ログインユーザーを投稿者として登録する
    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(New, self).form_valid(form)


class Edit(UpdateView):
    template_name = 'postapp/edit.html'
    model = Post
    fields = ('picture1', 'picture2', 'picture3', 'picture4', 'text')
    success_url = reverse_lazy('postapp:index')


class Delete(DeleteView):
    model = Post
    success_url = reverse_lazy('postapp:index')


class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'postapp/signup.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('profname')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('postapp:index')
        return render(request, 'postapp/signup.html', {'form': form})


class Login(LoginView):
    form_class = LoginForm
    template_name = 'postapp/login.html'
    

class Logout(LogoutView):
    template_name = 'postapp/index.html'


class ProfileView(DetailView):
    model = User
    template_name = 'postapp/profile.html'

    slug_field = 'profname'
    slug_url_kwarg = 'profname'


    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data()
    #     like_list = {}
    #     comment_list = {}
    #     post_list = Post.objects.all()
    #     for post in context['post_list']:
    #         like_list[post.id] = Like.objects.filter(post=post)
    #         comment_list[post.id] = Comment.objects.filter(post=post)
    #     context['like_list'] = like_list
    #     context['comment_list'] = comment_list
    #     comment['posts_list'] = Post.objects.all()
    #     return context


@login_required
def follow_view(request, *args, **kwargs):
    try:
        follower = User.objects.get(profname=request.user.profname)
        following = User.objects.get(profname=kwargs['profname'])
    except User.DoesNotExist:
        messages.warning(request, '{}は存在しません'.format(kwargs['profname']))
        return HttpResponseRedirect(reverse_lazy('postapp:index'))

    if follower == following:
        messages.warning(request, '自分自身はフォローできません')
    else:
        _, created = Connection.objects.get_or_create(follower=follower, following=following)

        if (created):
            messages.success(request, '{}をフォローしました'.format(following.profname))
        else:
            messages.warning(request, 'すでに{}をフォロー中です'.format(following.profname))

    return HttpResponseRedirect(reverse_lazy('postapp:profile', kwargs={'profname': following.profname}))

@login_required
def unfollow_view(request, *args, **kwargs):
    try:
        follower = User.objects.get(profname=request.user.profname)
        following = User.objects.get(profname=kwargs['profname'])
        if follower == following:
            messages.warning(request, '自分自身のフォローを外せません')
        else:
            unfollow = Connection.objects.get(follower=follower, following=following)
            unfollow.delete()
            messages.success(request, '{}のフォローを外しました'.format(following.profname))
    except User.DoesNotExist:
        messages.warning(request, '{}は存在しません'.format(kwargs['profname']))
        return HttpResponseRedirect(reverse_lazy('postapp:index'))
    except Connection.DoesNotExist:
        messages.warning(request, '{0}をフォローしませんでした'.format(following.profname))

    return HttpResponseRedirect(reverse_lazy('postapp:profile', kwargs={'profname': following.profname}))




class ProfileEditView(UpdateView):
    model = User
    # form_class = ProfileForm
    fields = ['icon', 'proftext']
    # success_url = reverse_lazy('postapp:index')

    def get_object(self):
        # ログイン中のユーザーで検索することを明示する
        return self.request.user

    def get_success_url(self):
           profname = self.kwargs['profname']
           return reverse_lazy('postapp:profile', kwargs={'profname': profname})



class Likes(View):
    model = Like
    slug_field = 'post'# モデルのフィールドの名前
    slug_url_kwarg = 'postId'# urls.pyでのキーワードの名前

    def get(self, request, postId):
        post = Post.objects.get(id=postId)
        like = Like.objects.filter(author=self.request.user, post=post)
        like_list = {}
        comment_list = {}
        # 過去にいいねを押しているのか
        if like.exists():
            # いいねされていれば消す
            like.delete()
        else: 
            # いいねされていなければ追加する
            like = Like(author=self.request.user, post=post)
            like.save()
        like_list[post.id] = Like.objects.filter(post=post)
        comment_list[post.id] = Comment.objects.filter(post=post)
        return render(request, 'postapp/like.html', {
            'like_list': like_list,
            'comment_list': comment_list,
            'post': post
        })


class AddComment(View):
    def post(self, request, postId):
        like_list = {}
        comment_list = {}

        post = Post.objects.get(id=postId)
        text = request.POST["comment"]

        comment = Comment(author=self.request.user, post=post, text=text)
        comment.save()

        like_list[post.id] = Like.objects.filter(post=post)
        comment_list[post.id] = Comment.objects.filter(post=post)
        return render(request, 'postapp/comment.html', {
            'like_list': like_list,
            'comment_list': comment_list,
            'post': post
        })


class DeleteComment(DeleteView):
    model = Comment
    template_name = 'postapp/comment_delete.html'
    success_url = reverse_lazy('postapp:index')

templates/postapp/profile.html
{% extends 'postapp/base.html' %}
{% load custom_filter %}
{% load static %}

{% block customcss %}
<link href="{% static 'postapp/profile.css' %}" rel="stylesheet">
{% endblock customcss %}

{% block content %}

<!--Section: Testimonials v.1-->
<section class="section pb-3 text-center">

  <!--Section heading-->
  <h1 class="section-heading h1 pt-4">Profile</h1>

  <div class="row">
    <!--Grid column-->
    <div class="mb-4 profile_card">

      <!--Card-->
      <div class="card testimonial-card">

        <!--Background color-->
        <div class="card-up blue lighten-2">
        </div>
        <!-- リクエストユーザーとユーザーのIDが同じなら編集可能 -->
        {% if request.user.id == user.id %}
        <a href="{% url 'postapp:profile_edit' user.profname %}" data-toggle="modal" data-target="#profile_EditModalForm"
          class="profile_edit">編集</a>
        {% endif %}

        <!--Avatar-->
        <div class="profile-card-contents">
          <div class="avatar white"><img src="/media/{{ user.icon }}" width="300px" alt="avatar mx-auto white"
             class="mt-4 rounded-circle">
          </div>
          <div class="favorite">
            <!--Name-->
            <h3 class="card-title">{{ user.profname }}</h3>
            <div class="favorite-button">
                <a href="{% url 'postapp:follow' user.profname %}" class="follow-link">　Follow　</a>
                <a href="{% url 'postapp:unfollow' user.profname %}" class="unfollow-link">Unfollow</a>
            </div>
            <!-- メッセージフレームワーク -->
            {% if messages %}
            {% for message in messages %}
            <div class="result-text">
                <p>{{ message }}</p>
            </div>
            {% endfor %}
            {% endif %}
            <hr style="margin: 30px;">

            <div class="connection">
                <p>Following<span class="num">{{ user.follower.count }}</span></p>
                <p>Followers<span class="num">{{ user.following.count }}</span></p>
            </div>
            <div class="card-body">
                <!--Quotation-->
                <p><i class="fas fa-quote-left"></i> {{ user.proftext }}</p>
            </div>
          </div>
        </div>


      </div>
      <!--Card-->

    </div>
    <!--Grid column-->


  



    <!-- Classic tabs -->
    <div class="classic-tabs container">
      <ul class="nav tabs-cyan" id="myClassicTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link  waves-light active show" id="profile-tab-classic" data-toggle="tab"
            href="#profile-classic" role="tab" aria-controls="profile-classic" aria-selected="true">投稿</a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-light" id="follow-tab-classic" data-toggle="tab" href="#follow-classic" role="tab"
            aria-controls="follow-classic" aria-selected="false">フォロワー</a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-light" id="contact-tab-classic" data-toggle="tab" href="#contact-classic" role="tab"
            aria-controls="contact-classic" aria-selected="false">フォロー中</a>
        </li>
      </ul>
      <div class="tab-content border-right border-bottom border-left rounded-bottom" id="myClassicTabContent">
        <div class="tab-pane fade active show clearfix" id="profile-classic" role="tabpanel"
          aria-labelledby="profile-tab-classic">
          <ul class="clearfix">
            {% for post in user.post_set.all %}
            <li>
                <a href="{% url 'postapp:edit' post.id %}" data-toggle="modal" data-target="#editModalForm-{{ post.id }}">
                    <img src="{{ post.picture1.url }}" width="90%;">
                </a>
                <!-- 編集モーダルコンテンツ -->
                {% include './edit.html' %}
                <!-- 編集モーダルコンテンツ -->
            </li>
            {% endfor %}
          </ul>
        </div>
        <div class="tab-pane fade" id="follow-classic" role="tabpanel" aria-labelledby="follow-tab-classic">
          <ul class="clearfix">
            {% for user in user.following.all %}
            <li>
                <a href="{% url 'postapp:profile' user.follower.profname %}"><img src="{{ user.follower.icon.url }}" class="follower-image"></a>
            </li>
            {% endfor %}
          </ul>
        </div>
        <div class="tab-pane fade" id="contact-classic" role="tabpanel" aria-labelledby="contact-tab-classic">
          <ul class="clearfix">
            {% for user in user.follower.all %}
            <li>
                <a href="{% url 'postapp:profile' user.following.profname %}"><img src="{{ user.following.icon.url }}" class="follower-image"></a>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
    <!-- Classic tabs -->

</section>
<!--Section: Testimonials v.1-->


<!-- プロフィールモーダルここから -->
<!-- Modal -->
<div class="modal fade" id="profile_EditModalForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <!--Content-->
    <div class="modal-content form-elegant">
      <!--Header-->
      <div class="modal-header text-center">
        <h3 class="modal-title w-100 dark-grey-text font-weight-bold my-3" id="myModalLabel"><strong>Profile
            Edit</strong>
        </h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <!--Body-->
      <div class="modal-body mx-4">
        <!--Avatar-->
        <div class="avatar mx-auto white text-center"><img src="/media/{{ user.icon }}" width="300px"
            alt="avatar mx-auto white" class="mt-4 rounded-circle">
        </div>

        <!--Body-->
        <form id="profile_edit" action="{% url 'postapp:profile_edit' user.profname %}" method="POST"
          enctype="multipart/form-data">
          {% csrf_token %}
          <div class="md-form pb-3">
            <div class="custom-file">
              <input type="file" class="custom-file-input " name="icon" id="{{ user.profname }}">
              <label class="custom-file-label" for="customFile">{{ user.icon }}</label>
            </div>
          </div>
          <div class="md-form mb-5">
            <input type="text" name="proftext" id="Form-email1" class="form-control validate"
              value="{{ user.proftext }}">
            <label data-error="wrong" data-success="right" for="Form-email1">PR</label>
          </div>
          <div class="text-center mb-3">
            <input type="submit" value="保存" class="btn blue-gradient btn-block btn-rounded z-depth-1a">
            <input type="hidden" name="next" value="{{ next }}">
          </div>
        </form>
      </div>
      <!--Footer-->

      <div class="modal-footer mx-5 pt-3 mb-1">
        <p class="font-small grey-text d-flex justify-content-end"><a href="#" class="blue-text ml-1">
            Sign Up</a></p>
      </div>
    </div>
    <!--/.Content-->
  </div>
</div>
<!-- Modal -->
<!-- プロフィールモーダルここまで -->


{% endblock content %}

templates/postapp/tag_detail.html
{% extends 'postapp/base.html' %}
{% load custom_filter %}
{% load static %}

{% block customcss %}
<link href="{% static 'postapp/index.css' %}" rel="stylesheet">
{% endblock customcss %}

{% block content %}
<div class="container clearfix">
  <div class="search-form">
    <input class="form-control search-text" type="text" placeholder="# {{ tag.name }}" aria-label="Search">
  </div>
  
  {% for post in tag.post_set.all %}
  <div class="postcard">
    <div class="card">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <a href="{% url 'postapp:profile' post.pk %}" class="text-dark"><img src="media/{{ post.author.icon }}"
              width="50px;" class="timeline-icon rounded-circle" style="height:3%">
            <span class="span_profname">{{ post.author.profname }}</span>
          </a>
        </li>
      </ul>
      <!--画像モーダルここから-->
      <a data-toggle="modal" data-target="#modal-follow-{{ post.id }}">
        <div class="hovereffect">
          <img class="img-responsive card-img pc_mainimg" src="{{post.picture1.url}}">
          <div class="overlay spblock">
            <span><i class="fas fa-heart"></i></span>

            <h2>{{ post.like_set.count }}</h2>
            <span class="comment_text_hover" style="margin-left: 20px;"><i class="fas fa-comment"></i></span>

            <h2>{{ post.comment_set.count }}</h2>

          </div>
        </div>
      </a>
      <!--モーダル適用ここまで-->

      <!-- トップ表示ここから -->
      <div class="card-body">
        <!--Ajax追加文-->
        <div class="like_list_{{post.id}}">
          <!--ハート-->
          {{ post|is_like:user }}
          <!--profnameがいいねしました-->
          <span class="like_text">{{ like_list|get_likes:post.id }}</span>
        </div>
        <div class="card-hedder">
          <!--本文-->
          {{ post.text |truncatechars:18 }}
        </div>
        <div class="post_tag">
          {% for tag in post.tag.all %}
          <a href="{% url 'postapp:tag' tag.pk %}">#{{ tag.name }}</a>
          {% endfor  %}

        </div>

        <div class="card-hedder">
          <a data-toggle="modal" data-target="#modal-follow-{{ post.id }}">
            <span class="comment_text"><i class="far fa-comment" style="font-size: 15px;"></i>
              コメントする</span>
          </a>
        </div>
        <div class="pt-2">
          <!-- <small>
                            投稿時間 {{ post.created_at|date:'m/d H:i' }} <div id="header123">
                            </div>
                        </small> -->
          <a href="{% url 'postapp:profile' post.author.id %}"><img src="{{ post.author.icon.url }}" class="top-icon"
              width="40"></a>
        </div>
      </div>
      <!-- トップ表示ここまで -->


      <!--モーダルの中身-->
      <div id="modal-follow-{{ post.id }}" class="modal fade">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <a href="{% url 'postapp:profile' post.author.id %}" class="text-dark"><img
                  src="{{ post.author.icon.url }}" width="50px;" class="timeline-icon rounded-circle float-left"
                  style="height:3%">
                <span class="span_profname">{{ post.author.profname }}</span>
              </a>
              <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                <span aria-hidden="true">&times;</span>
              </button>
              <div class="user_set">
                <a href="{% url 'postapp:edit' post.id %}" data-toggle="modal"
                  data-target="#editModalForm-{{ post.id }}">編集</a>　
                <a href="{% url 'postapp:delete' post.id %}" data-toggle="modal"
                  data-target="#exampleModalCenter">削除</a>
              </div>
            </div>
            <div class="modal-body">
              <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <div class="post_img carousel-inner">
                  <div class="carousel-item active">
                    <img class="img-responsive card-img" src="{{post.picture1.url}}">
                  </div>
                  <div class="carousel-item">
                    <img class="img-responsive card-img" src="{{post.picture2.url}}">
                  </div>
                  <div class="carousel-item">
                    <img class="img-responsive card-img" src="{{post.picture3.url}}">
                  </div>
                  <div class="carousel-item">
                    <img class="img-responsive card-img" src="{{post.picture4.url}}">
                  </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="sr-only">前の画像</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="sr-only">次の画像</span>
                </a>
              </div><!-- /.carousel -->

              <div class="post_contents">
                <div class="post_icon">
                  <a href="{% url 'postapp:profile' post.author.id %}" class="text-dark"><img
                      src="{{ post.author.icon.url }}" width="50px;" class="timeline-icon rounded-circle"
                      style="height:3%">
                    <span class="span_profname">{{ post.author.profname }}</span>
                  </a>
                </div>
                <div class="post_text">
                  <p>{{ post.text }}</p>
                </div>
                <div class="post_comment">
                  <div class="like_list_{{post.id}}">
                    <!--Ajax追加文-->
                    {{ post|is_like:user }}
                    <!--ハート-->
                    <span class="like_text">{{ like_list|get_likes:post.id }}</span><!--profnameがいいねしました-->
                    <!--profnameがいいねしました-->
                  </div>
                  <!--Ajax新規追加文-->
                  <div class="comment_list_{{post.id}} comments">
                    <!--既存コメント-->
                    <p>{{ comment_list|get_comment_list2:post.id }}</p>
                  </div>
                  <!-- <div class="like_list_{{post.id}}"></div>

                  <a href="{% url 'postapp:delete_comment' post.id %}">コメ削除</a> -->

                  <form class="comment" id="{{ post.id }}">
                    {% csrf_token %}
                    <input class="form-control comment" name="comment" type="text" placeholder="コメント">
                  </form>
                </div>
              </div>
            </div>
            <div class="modal-footer justify-content-between">
              <form method="POST" action="">
                <button type="button" class="btn blue-gradient btn-block btn-rounded z-depth-1a"
                  data-dismiss="modal">戻る</button>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!--モーダルの中身ここまで-->

      <!-- 投稿モーダルコンテンツ -->
      {% include './new.html' %}
      <!-- 投稿モーダルコンテンツ -->

      <!-- 編集モーダルコンテンツ -->
      {% include './edit.html' %}
      <!-- 編集モーダルコンテンツ -->


      <!-- 投稿削除モーダルコンテンツ -->
      {% include './delete.html' %}
      <!-- 投稿削除モーダルコンテンツ -->
      
      <!-- コメント削除モーダルコンテンツ -->
      {% include './comment_delete.html' %}
      <!-- コメント削除モーダルコンテンツ -->
    </div>
  </div>
  {% endfor %}
</div>

<script>
  $(document) //HTML読み込み後に処理実行
    .on('click', '.like', function () {
      var id = $(this).attr("id");
      do_like(id)
    })

  $('.post_comment').on('submit', 'form', function () { //イベント名、セレクタ、関数
    do_comment($(this))
    $(this).find(":text").val("")
    return false
  })


  function do_like(post_id) {
    $.ajax({
      url: `./${post_id}/like`,
      type: 'get'
    })
      .done((data) => {
        $('.like_list_' + post_id).html(data);
      })
  }


  function do_comment(form) {
    console.log(form.serialize())
    $.ajax({
      url: `./${form.attr("id")}/comment/`,
      type: 'post',
      data: form.serialize(),
    })
      .done((data) => {
        $('.like_list_' + form.attr("id")).html(data);
      })
  }
</script>

{% endblock content %}